"""Topic (pattern) definitions for the DSA course.

Single source of truth for:
  - the ordered list of pattern Parts,
  - which classifier buckets feed each Part,
  - the primer outline for each Part.

`data/bb_questions.json` holds the 1213 Bloomberg-tagged LeetCode questions,
each already classified into one bucket. Everything else is generated from these two.
"""

# (part_slug, number, title, [buckets], one-line "what this pattern is", primer outline)
PATTERNS = [
    ("arrays-hashing", 1, "Arrays, Hashing and Prefix Sums",
     ["arrays-hashing", "prefix-sum"],
     "Trade memory for time: a dict or a running total turns a nested loop into one pass.",
     ["What a hash table actually is (buckets, load factor, resize, collisions)",
      "Recognition signals: 'have I seen', 'count of', 'pair that sums'",
      "The complement trick (Two Sum family)",
      "Frequency maps and Counter idioms",
      "Prefix sums: 1D, 2D, and prefix-sum + hashmap for subarray targets",
      "Difference arrays for range updates",
      "Python: dict, defaultdict, Counter, set - costs and gotchas"]),

    ("two-pointers", 2, "Two Pointers",
     ["two-pointers"],
     "Two indices moving under an invariant, usually on a sorted array or from both ends.",
     ["Opposite-ends pointers (sorted pair sum, container with most water)",
      "Same-direction (fast/slow) pointers and in-place compaction",
      "Why sorting first is often the whole trick",
      "Dedup logic in k-sum problems",
      "Partitioning (Dutch national flag)",
      "Proving the pointer move is safe - the exchange argument"]),

    ("sliding-window", 3, "Sliding Window",
     ["sliding-window"],
     "A contiguous window that grows on the right and shrinks on the left while a condition holds.",
     ["Fixed-size vs variable-size windows",
      "The universal template (expand, violate, contract, record)",
      "Window state: counter, distinct count, sum, max in window",
      "At-most-K trick for exactly-K problems",
      "When a window is NOT valid (negative numbers, non-monotonic conditions)",
      "Amortised O(n) argument"]),

    ("stack-queue", 4, "Stacks, Queues and Monotonic Stacks",
     ["stack-queue", "monotonic-stack"],
     "LIFO for matching and nesting; monotonic stacks for next-greater and span problems.",
     ["Matching and nesting (parentheses, path simplification)",
      "Expression evaluation and the calculator family",
      "Monotonic stack: next greater / previous smaller",
      "Histogram and trapping-water as span problems",
      "Monotonic deque for sliding window maximum",
      "Stack-based iterative traversal as a recursion replacement"]),

    ("binary-search", 5, "Binary Search",
     ["binary-search"],
     "Halve a search space that is monotone in the answer - not just sorted arrays.",
     ["The two invariants (lower_bound / upper_bound) and why off-by-one bugs happen",
      "bisect_left vs bisect_right, and rolling your own",
      "Binary search on the answer (minimise the maximum)",
      "Rotated and modified sorted arrays",
      "Search in 2D matrices",
      "Predicate framing: find the first True in a FFFTTT sequence"]),

    ("sorting", 6, "Sorting and Custom Ordering",
     ["sorting"],
     "Choosing the right key, comparator, or counting scheme - often the entire solution.",
     ["Comparison sorts vs counting/radix/bucket sort",
      "Python sort: key functions, stability, functools.cmp_to_key",
      "Custom alphabets and non-standard collation orders",
      "Sorting by multiple criteria and by derived scores",
      "Quickselect for k-th order statistics",
      "When NOT to sort (heap, counting, or bucketing is cheaper)"]),

    ("linked-list", 7, "Linked Lists",
     ["linked-list"],
     "Pointer surgery: dummy heads, fast/slow pointers, and careful re-linking.",
     ["Dummy-head pattern and why it removes edge cases",
      "Reversal: iterative, recursive, and in k-groups",
      "Fast/slow pointers: middle, cycle detection, cycle start (Floyd)",
      "Merging and partitioning lists",
      "Doubly and multilevel lists (flatten)",
      "Drawing the pointers before writing code"]),

    ("trees", 8, "Trees and Binary Search Trees",
     ["trees"],
     "Recursion with a clear contract: what the call returns and what the parent does with it.",
     ["Traversals: preorder, inorder, postorder, level-order (and iterative forms)",
      "The recursive contract: define the return value first",
      "BST invariant and why inorder is sorted",
      "Lowest common ancestor family",
      "Path problems (root-to-leaf, any-to-any, path sums)",
      "Serialisation and reconstruction from traversals",
      "Height, balance, diameter - postorder aggregation"]),

    ("trie", 9, "Tries and Prefix Structures",
     ["trie"],
     "A tree keyed by characters - makes prefix queries O(length) instead of O(corpus).",
     ["Node design: dict of children vs fixed array; is_word flag",
      "Insert, search, startsWith",
      "Autocomplete: top-k completions per prefix",
      "Wildcard and regex-lite matching over a trie",
      "Bitwise trie for XOR maximisation",
      "Memory cost and when a sorted list + binary search is better"]),

    ("heap", 10, "Heaps and Top-K",
     ["heap"],
     "Keep only what you need: a size-k heap answers top-k in O(n log k).",
     ["Binary heap mechanics: sift up/down, heapify in O(n)",
      "Min-heap of size k for top-k largest (and why it is inverted)",
      "heapq API, tuples as keys, lazy deletion, the (priority, counter, item) idiom",
      "Two-heap median maintenance",
      "K-way merge",
      "Heap vs quickselect vs bucket sort for top-k"]),

    ("intervals", 11, "Intervals and Line Sweep",
     ["intervals"],
     "Sort by an endpoint, then sweep - almost every interval problem reduces to this.",
     ["Merge / insert / erase intervals",
      "Overlap test and the two canonical sorts (by start vs by end)",
      "Line sweep with +1/-1 events (meeting rooms, max concurrency)",
      "Min-heap of end times as an alternative sweep",
      "Interval scheduling (greedy, by earliest end)",
      "Intervals that wrap past midnight and other real-world edge cases"]),

    ("greedy", 12, "Greedy",
     ["greedy"],
     "Take the locally best move - and be ready to prove it stays globally optimal.",
     ["Exchange argument: the standard proof sketch to say out loud",
      "Sort-then-scan greedies",
      "Greedy with a heap (regret / replacement greedies)",
      "Jump-game style reachability greedies",
      "Stock buy/sell family",
      "How to tell greedy from DP (and how to fall back safely)"]),

    ("backtracking", 13, "Recursion and Backtracking",
     ["backtracking"],
     "Enumerate a decision tree, undo each choice, and prune as early as possible.",
     ["The choose / explore / un-choose template",
      "Subsets, permutations, combinations - and their dedup rules",
      "Pruning: sorting, bounds, and feasibility checks",
      "Grid backtracking (word search, path enumeration)",
      "Constraint problems (n-queens, sudoku)",
      "Complexity of exponential search and how to state it"]),

    ("graphs", 14, "Graphs, Grids and Union-Find",
     ["graphs"],
     "Model the problem as nodes and edges first; the algorithm is then almost forced.",
     ["Representations: adjacency list, matrix, implicit grids",
      "BFS (shortest path in unweighted graphs) and DFS (connectivity, paths)",
      "Grid traversal / flood fill and the boundary trick",
      "Topological sort (Kahn and DFS) and cycle detection",
      "Dijkstra, Bellman-Ford, and when each is needed",
      "Union-Find with path compression and union by rank",
      "Enumerating all paths vs shortest path - different tools",
      "Bipartite checking and colouring"]),

    ("dp", 15, "Dynamic Programming",
     ["dp"],
     "Define the state, write the recurrence, then decide memo or table.",
     ["Optimal substructure and overlapping subproblems - how to verify both",
      "State design: what is the smallest thing that determines the rest",
      "Top-down memoisation vs bottom-up tabulation, and space rolling",
      "1D: climbing stairs, house robber, coin change, LIS",
      "2D: grid paths, edit distance, LCS, knapsack",
      "Interval DP and partition DP",
      "DP on strings with matching (regex, wildcard, word break)",
      "Bitmask DP",
      "Reconstructing the answer, not just its value"]),

    ("bit", 16, "Bit Manipulation",
     ["bit"],
     "XOR cancellation, masks, and the handful of tricks that keep reappearing.",
     ["AND/OR/XOR/shift semantics and Python's arbitrary-precision ints",
      "XOR identities: a^a=0, a^0=a, and the single-number family",
      "Low bit isolation x & -x, clearing x & (x-1), popcount",
      "Bitmask as a set (subset enumeration)",
      "Building addition/multiplication without operators",
      "Signed-integer simulation and 32-bit overflow in Python"]),

    ("math", 17, "Math, Number Theory and Geometry",
     ["math"],
     "Primes, modular arithmetic, digit manipulation, randomisation and coordinate geometry.",
     ["Overflow, integer parsing and clamping (atoi, reverse integer)",
      "GCD/LCM, Euclid, and modular inverse",
      "Primes: trial division, sieve, segmented sieve, factorisation",
      "Fast exponentiation (binary and modular)",
      "Digit DP-lite: counting and constructing numbers",
      "Random sampling and reservoir sampling",
      "Geometry: points, slopes, clock angles, rectangle overlap"]),

    ("matrix", 18, "Matrix and Simulation",
     ["matrix"],
     "Index arithmetic done carefully, plus problems that simply ask you to follow the rules.",
     ["In-place rotation, transpose, and reflection",
      "Spiral and diagonal traversal",
      "Using the first row/column as marker storage",
      "Game-of-life style in-place state encoding",
      "Direction vectors and boundary handling",
      "Simulation problems: read the spec twice, then encode it literally"]),

    ("strings", 19, "Strings and Parsing",
     ["strings"],
     "Tokenising, comparing and transforming text - plus the pattern-matching classics.",
     ["Python string costs: immutability, slicing, join vs +=",
      "Palindromes: two-pointer, expand-around-centre, DP",
      "Anagram signatures (sorted key vs count key)",
      "Parsing: tokenising, nesting, and recursive descent (decode string, calculator)",
      "Substring search: naive, KMP, Rabin-Karp",
      "Encoding/decoding and run-length compression",
      "Word-splitting with a dictionary (trie + DP)"]),

    ("design", 20, "Data Structure Design",
     ["design"],
     "Compose two structures so every operation hits its target complexity.",
     ["The design-round recipe: list operations, target complexity, pick structures",
      "Hash map + doubly linked list (LRU) and hash map + array (O(1) random)",
      "Hash map + heap, and the lazy-deletion pattern",
      "Time-indexed stores and binary search over timestamps",
      "Iterators, streams and lazy evaluation",
      "Thread-safety and what to say if asked",
      "Writing clean class APIs under time pressure"]),

    ("concurrency", 21, "Concurrency and Python Internals",
     ["concurrency"],
     "The things Bloomberg asks after the algorithm: how does this actually run.",
     ["How dict and set really work (hashing, probing, resize) - a frequent follow-up",
      "Mutable default arguments, shallow vs deep copy, identity vs equality",
      "GIL, threads vs processes vs asyncio",
      "Locks, semaphores, condition variables, producer-consumer",
      "Generators and memory-bounded stream processing",
      "Reference counting, garbage collection, and __slots__"]),
    ("sql-lang", 22, "SQL, Shell and Language-Specific (secondary track)",
     ["sql", "lang-specific"],
     "Not the new-grad coding round, but tagged for Bloomberg and worth a weekend.",
     ["SELECT, JOIN types, and what an interviewer means by 'the second highest'",
      "GROUP BY, HAVING, and aggregate gotchas with NULL",
      "Window functions: ROW_NUMBER, RANK, DENSE_RANK, LAG/LEAD",
      "Self joins and correlated subqueries",
      "Writing a query that reads like the question",
      "The JavaScript and pandas tagged problems - skim only unless the role asks"]),
]

BUCKET_TO_PART = {b: p[0] for p in PATTERNS for b in p[3]}
PART_BY_SLUG = {p[0]: p for p in PATTERNS}
