events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr info;

    upstream grpc_backend {
        server 127.0.0.1:50061;
        server 127.0.0.1:50062;
    }

    server {
        listen 8080;
        http2 on;

        location / {
            grpc_pass grpc://grpc_backend;
        }
    }
}
